// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.EntityFrameworks
{
    [Keyless]
    public partial class Config
    {
        public long IDempresa { get; set; }
        public long IP { get; set; }
        [Required]
        [StringLength(150)]
        public string SSID_Int { get; set; }
        [Required]
        [StringLength(150)]
        public string PASS_Int { get; set; }
        [StringLength(150)]
        public string SSID_Ext { get; set; }
        [StringLength(150)]
        public string PASS_Ext { get; set; }

        [ForeignKey(nameof(IDempresa))]
        public virtual Empresas IDempresaNavigation { get; set; }
    }
}