// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.EntityFrameworks
{
    public partial class Data
    {
        [Key]
        public long ID { get; set; }
        public long IDequipment { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }
        public int Count { get; set; }
        [Required]
        [Column("Data")]
        public string Data1 { get; set; }
        [StringLength(50)]
        public string Aux { get; set; }

        [ForeignKey(nameof(IDequipment))]
        [InverseProperty(nameof(Equipments.Data))]
        public virtual Equipments IDequipmentNavigation { get; set; }
    }
}