// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.EntityFrameworks
{
    public partial class Data
    {
        [Key]
        public long ID { get; set; }
        public long IDclient { get; set; }
        public long IDstation { get; set; }
        public long IDequipment { get; set; }
        public long Timespan { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Datetime { get; set; }
        public int Count { get; set; }
        [Required]
        public string Info { get; set; }
        [StringLength(50)]
        public string Aux { get; set; }

        [ForeignKey(nameof(IDclient))]
        [InverseProperty(nameof(Clients.Data))]
        public virtual Clients IDclientNavigation { get; set; }
        [ForeignKey(nameof(IDequipment))]
        [InverseProperty(nameof(Equipments.Data))]
        public virtual Equipments IDequipmentNavigation { get; set; }
        [ForeignKey(nameof(IDstation))]
        [InverseProperty(nameof(Stations.Data))]
        public virtual Stations IDstationNavigation { get; set; }
    }
}