// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.EntityFrameworks
{
    public partial class Datos
    {
        [Key]
        public long ID { get; set; }
        public long IDdron { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaHora { get; set; }
        [Required]
        public string Dato { get; set; }

        [ForeignKey(nameof(IDdron))]
        [InverseProperty(nameof(Drones.Datos))]
        public virtual Drones IDdronNavigation { get; set; }
    }
}