// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.EntityFrameworks
{
    public partial class Equipments
    {
        public Equipments()
        {
            Data = new HashSet<Data>();
        }

        [Key]
        public long ID { get; set; }
        [Required]
        [StringLength(50)]
        public string IDstatus { get; set; }
        public long IDstation { get; set; }
        [Required]
        [StringLength(50)]
        public string MAC { get; set; }

        [ForeignKey(nameof(IDstation))]
        [InverseProperty(nameof(Stations.Equipments))]
        public virtual Stations IDstationNavigation { get; set; }
        [InverseProperty("IDequipmentNavigation")]
        public virtual ICollection<Data> Data { get; set; }
    }
}