// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.EntityFrameworks
{
    public partial class Logs_SystemMoves
    {
        [Key]
        public long ID { get; set; }
        public long IDclient { get; set; }
        public long IDuser { get; set; }
        [Required]
        [StringLength(50)]
        public string IDstatus { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }
        [Required]
        [StringLength(500)]
        public string Detail { get; set; }
        [StringLength(50)]
        public string Aux { get; set; }

        [ForeignKey(nameof(IDclient))]
        [InverseProperty(nameof(Clients.Logs_SystemMoves))]
        public virtual Clients IDclientNavigation { get; set; }
        [ForeignKey(nameof(IDuser))]
        [InverseProperty(nameof(Users.Logs_SystemMoves))]
        public virtual Users IDuserNavigation { get; set; }
    }
}