// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.EntityFrameworks
{
    public partial class Logs_MovimientosDelSistema
    {
        [Key]
        public long ID { get; set; }
        public long IDempresa { get; set; }
        public long IDusuario { get; set; }
        [Required]
        [StringLength(50)]
        public string IDestado { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Fecha { get; set; }
        [Required]
        [StringLength(500)]
        public string Detalle { get; set; }
        [StringLength(50)]
        public string Aux { get; set; }

        [ForeignKey(nameof(IDempresa))]
        [InverseProperty(nameof(Empresas.Logs_MovimientosDelSistema))]
        public virtual Empresas IDempresaNavigation { get; set; }
        [ForeignKey(nameof(IDusuario))]
        [InverseProperty(nameof(Usuarios.Logs_MovimientosDelSistema))]
        public virtual Usuarios IDusuarioNavigation { get; set; }
    }
}