// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.EntityFrameworks
{
    public partial class Logs_Errors
    {
        [Key]
        public long ID { get; set; }
        public long IDuser { get; set; }
        public long IDcompany { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }
        [StringLength(150)]
        public string System { get; set; }
        [StringLength(50)]
        public string Code { get; set; }
        [StringLength(250)]
        public string Commentary { get; set; }
        [StringLength(50)]
        public string Action { get; set; }
        [StringLength(50)]
        public string Aux { get; set; }
        public string Exception { get; set; }
        public string Exception_File { get; set; }
        public string Exception_Method { get; set; }
        public string Exception_NumberOfLine { get; set; }
        public string Exception_Source { get; set; }
        public string Exception_Message { get; set; }

        [ForeignKey(nameof(IDcompany))]
        [InverseProperty(nameof(Companies.Logs_Errors))]
        public virtual Companies IDcompanyNavigation { get; set; }
        [ForeignKey(nameof(IDuser))]
        [InverseProperty(nameof(Users.Logs_Errors))]
        public virtual Users IDuserNavigation { get; set; }
    }
}