// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.EntityFrameworks
{
    public partial class Logs_Errores
    {
        [Key]
        public long ID { get; set; }
        public long IDusuario { get; set; }
        public long IDempresa { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Fecha { get; set; }
        [StringLength(150)]
        public string Sistema { get; set; }
        [StringLength(50)]
        public string Codigo { get; set; }
        [StringLength(250)]
        public string Comentario { get; set; }
        [StringLength(50)]
        public string Accion { get; set; }
        [StringLength(50)]
        public string Aux { get; set; }
        public string Excepcion { get; set; }
        public string Excepcion_Archivo { get; set; }
        public string Excepcion_Metodo { get; set; }
        public string Excepcion_NumeroDeLinea { get; set; }
        public string Excepcion_Source { get; set; }
        public string Excepcion_Mensaje { get; set; }
    }
}