// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.EntityFrameworks
{
    public partial class Stations
    {
        public Stations()
        {
            Equipments = new HashSet<Equipments>();
        }

        [Key]
        public long ID { get; set; }
        [Required]
        [StringLength(50)]
        public string IDstatus { get; set; }
        public long IDcompany { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        public long IP_Private { get; set; }
        public long IP_Public { get; set; }
        [Required]
        [StringLength(150)]
        public string SSID_Int { get; set; }
        [Required]
        [StringLength(150)]
        public string PASS_Int { get; set; }
        [StringLength(150)]
        public string SSID_Ext { get; set; }
        [StringLength(150)]
        public string PASS_Ext { get; set; }

        [ForeignKey(nameof(IDcompany))]
        [InverseProperty(nameof(Companies.Stations))]
        public virtual Companies IDcompanyNavigation { get; set; }
        [InverseProperty("IDstationNavigation")]
        public virtual ICollection<Equipments> Equipments { get; set; }
    }
}