// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Models.EntityFrameworks
{
    public partial class UNG_Context : DbContext
    {
        public UNG_Context()
        {
        }

        public UNG_Context(DbContextOptions<UNG_Context> options)
            : base(options)
        {
        }

        public virtual DbSet<Config> Config { get; set; }
        public virtual DbSet<Datos> Datos { get; set; }
        public virtual DbSet<Drones> Drones { get; set; }
        public virtual DbSet<Emails> Emails { get; set; }
        public virtual DbSet<Empresas> Empresas { get; set; }
        public virtual DbSet<Logs_Errores> Logs_Errores { get; set; }
        public virtual DbSet<Logs_MovimientosDelSistema> Logs_MovimientosDelSistema { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=.\\sqlexpress;Initial Catalog=UNG;Persist Security Info=True;User ID=nexus-sql;Password=Nexus@1699");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Modern_Spanish_CI_AS");

            modelBuilder.Entity<Config>(entity =>
            {
                entity.HasOne(d => d.IDempresaNavigation)
                    .WithMany()
                    .HasForeignKey(d => d.IDempresa)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Config_Empresas");
            });

            modelBuilder.Entity<Datos>(entity =>
            {
                entity.HasOne(d => d.IDdronNavigation)
                    .WithMany(p => p.Datos)
                    .HasForeignKey(d => d.IDdron)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Datos_Drones");
            });

            modelBuilder.Entity<Emails>(entity =>
            {
                entity.Property(e => e.ID).ValueGeneratedNever();
            });

            modelBuilder.Entity<Logs_MovimientosDelSistema>(entity =>
            {
                entity.HasOne(d => d.IDempresaNavigation)
                    .WithMany(p => p.Logs_MovimientosDelSistema)
                    .HasForeignKey(d => d.IDempresa)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Logs_MovimientosDelSistema_Empresas");

                entity.HasOne(d => d.IDusuarioNavigation)
                    .WithMany(p => p.Logs_MovimientosDelSistema)
                    .HasForeignKey(d => d.IDusuario)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Logs_MovimientosDelSistema_Usuarios");
            });

            modelBuilder.Entity<Usuarios>(entity =>
            {
                entity.HasOne(d => d.IDempresaNavigation)
                    .WithMany(p => p.Usuarios)
                    .HasForeignKey(d => d.IDempresa)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Usuarios_Empresas");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}