// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models.EntityFrameworks
{
    public partial class Users
    {
        public Users()
        {
            Logs_Errors = new HashSet<Logs_Errors>();
            Logs_SystemMoves = new HashSet<Logs_SystemMoves>();
        }

        [Key]
        public long ID { get; set; }
        public long IDcompany { get; set; }
        [Required]
        public string IDstatus { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string PasswordHash { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Surname { get; set; }
        [Required]
        public string DateOf_Creation { get; set; }
        public string DateOf_LastLogin { get; set; }
        public string PinRestorePassword { get; set; }

        [ForeignKey(nameof(IDcompany))]
        [InverseProperty(nameof(Companies.Users))]
        public virtual Companies IDcompanyNavigation { get; set; }
        [InverseProperty("IDuserNavigation")]
        public virtual ICollection<Logs_Errors> Logs_Errors { get; set; }
        [InverseProperty("IDuserNavigation")]
        public virtual ICollection<Logs_SystemMoves> Logs_SystemMoves { get; set; }
    }
}