// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APIAdmin.LocalModels.EntityFrameworks
{
    public partial class Clients
    {
        public Clients()
        {
            Equipments = new HashSet<Equipments>();
            Logs_Errors = new HashSet<Logs_Errors>();
            Logs_SystemMoves = new HashSet<Logs_SystemMoves>();
            Stations = new HashSet<Stations>();
            Users = new HashSet<Users>();
        }

        [Key]
        public long ID { get; set; }
        public long Modify_IDuser { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modify_Date { get; set; }
        [Required]
        [StringLength(50)]
        public string IDstatus { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        public string DateOf_Creation { get; set; }
        [StringLength(50)]
        public string? Aux { get; set; }

        [InverseProperty("IDclientNavigation")]
        public virtual ICollection<Equipments> Equipments { get; set; }
        [InverseProperty("IDclientNavigation")]
        public virtual ICollection<Logs_Errors> Logs_Errors { get; set; }
        [InverseProperty("IDclientNavigation")]
        public virtual ICollection<Logs_SystemMoves> Logs_SystemMoves { get; set; }
        [InverseProperty("IDclientNavigation")]
        public virtual ICollection<Stations> Stations { get; set; }
        [InverseProperty("IDclientNavigation")]
        public virtual ICollection<Users> Users { get; set; }
    }
}