// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APIAdmin.LocalModels.EntityFrameworks
{
    public partial class Users
    {
        public Users()
        {
            Equipments = new HashSet<Equipments>();
            Logs_Errors = new HashSet<Logs_Errors>();
            Logs_SystemMoves = new HashSet<Logs_SystemMoves>();
            Stations = new HashSet<Stations>();
        }

        [Key]
        public long ID { get; set; }
        [Required]
        public string IDstatus { get; set; }
        public int IDrole { get; set; }
        public long? IDclient { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string PasswordHash { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Surname { get; set; }
        [Required]
        public string DateOf_Creation { get; set; }
        public string DateOf_LastLogin { get; set; }
        public string PinRestorePassword { get; set; }
        public string JSONListOfPermissions { get; set; }
        [StringLength(150)]
        public string? Aux { get; set; }

        [ForeignKey(nameof(IDclient))]
        [InverseProperty(nameof(Clients.Users))]
        public virtual Clients IDclientNavigation { get; set; }
        [InverseProperty("Modify_IDuserNavigation")]
        public virtual ICollection<Equipments> Equipments { get; set; }
        [InverseProperty("IDuserNavigation")]
        public virtual ICollection<Logs_Errors> Logs_Errors { get; set; }
        [InverseProperty("IDuserNavigation")]
        public virtual ICollection<Logs_SystemMoves> Logs_SystemMoves { get; set; }
        [InverseProperty("Modify_IDuserNavigation")]
        public virtual ICollection<Stations> Stations { get; set; }
    }
}